test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.000005
momentum: 0.9
decay: 5e-4
S: 2
z: 0.6
dp: False
epochs: 60
save_on_epochs: [10, 20, 30, 40, 50]

mu: 1.0
ds_size: 70000

key_to_drop: 8
number_of_entries: 1000
number_of_entries_test: 1000


save_model: True
dataset: dif
model: dif_inception
densenet_depth: 100
scheduler: False
optimizer: Adam

root_dir: data/dif/images/
crop_list: data/dif/boxes_list.pt

#resumed_model: model_utk_May.09_11.07.46/model_last.pt.tar

#gender
#folder_per_class: data/dif/unbalanced/gender_skin
#class_list: data/dif/gender_list.pt
#indices_train: data/dif/gender_train_list.pt
#indices_test: data/dif/gender_test_list.pt

#age balanced
#folder_per_class: data/dif/unbalanced/gender_age
#class_list: data/dif/label_age_list.pt
#indices_train: data/dif/age_10k_ds_train.pt
#indices_test: data/dif/age_10k_ds_test.pt

# age unbalanced
#folder_per_class: data/dif/unbalanced/age_skin_unb/
#class_list: data/dif/label_age_list.pt
#indices_train: data/dif/age_unbalanced_train.pt
#indices_test: data/dif/age_unbalanced_test.pt

# highly unbalanced gneder
folder_per_class: data/dif/unbalanced/type1_type6/
class_list: data/dif/gender_list.pt
indices_train: data/dif/gender_new_train.pt
indices_test: data/dif/gender_new_test.pt



label_skin_list: data/dif/label_skin_list.pt

multi_gpu: False