test_batch_size: 100
batch_size: 64
num_microbatches: 64
lr: 0.1
momentum: 0.9
decay: 5e-4
S: 1
z: 0.6
dp: False
epochs: 60
save_on_epochs: [10, 50, 100, 200]

mu: 0.8
ds_size: 27000

save_model: False
dataset: cifar10
model: resnet
densenet_depth: 100
scheduler: True