test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.15
momentum: 0.5
decay: 0
S: 1
z: 0.9
dp: True
epochs: 60
save_on_epochs: [10, 50, 100, 200]

mu: 0.8
ds_size: 27000

save_model: False
dataset: mnist
model: net
densenet_depth: 100
scheduler: False