test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.00005
momentum: 0.9
decay: 5e-4
S: 1
z: 0.8
dp: True
epochs: 60
save_on_epochs: [10, 20, 40, 60]

mu: 1.0
ds_size: 70000

key_to_drop: 8
number_of_entries: 1000
number_of_entries_test: 1000


save_model: True
dataset: dif
model: PretrainedRes
densenet_depth: 100
scheduler: False
optimizer: Adam

root_dir: /home/eugene/dpf/data/dif/images/
crop_list: /home/eugene/dpf/data/dif/boxes_list.pt

#resumed_model: model_utk_May.09_11.07.46/model_last.pt.tar

#gender
#folder_per_class: data/dif/unbalanced/gender_skin
#class_list: /home/eugene/dpf/data/dif/gender_list.pt
#indices_train: /home/eugene/dpf/data/dif/gender_train_list.pt
#indices_test: /home/eugene/dpf/data/dif/gender_test_list.pt

#age balanced
#folder_per_class: data/dif/unbalanced/gender_age
#class_list: /home/eugene/dpf/data/dif/label_age_list.pt
#indices_train: /home/eugene/dpf/data/dif/age_10k_ds_train.pt
#indices_test: /home/eugene/dpf/data/dif/age_10k_ds_test.pt

# age unbalanced
folder_per_class: data/dif/unbalanced/age_skin_unb/
class_list: /home/eugene/dpf/data/dif/label_age_list.pt
indices_train: /home/eugene/dpf/data/dif/age_unbalanced_train.pt
indices_test: /home/eugene/dpf/data/dif/age_unbalanced_test.pt


label_skin_list: data/dif/label_skin_list.pt