test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.001
momentum: 0.9
decay: 5e-4
S: 1
z: 0.8
dp: True
epochs: 40
save_on_epochs: [10, 50, 100, 200]

mu: 1.0
ds_size: 60000

key_to_drop: 8
number_of_entries: 1000
number_of_entries_test: 1000


save_model: True
dataset: dif
model: resnet
densenet_depth: 100
scheduler: False
optimizer: Adam

folder_per_class: data/dif/unbalanced

class_list: /home/eugene/dpf/data/dif/gender_list.pt
root_dir: /home/eugene/dpf/data/dif/images/
crop_list: /home/eugene/dpf/data/dif/boxes_list.pt

indices_train: /home/eugene/dpf/data/dif/gender_train_list.pt
indices_test: /home/eugene/dpf/data/dif/gender_test_list.pt