test_batch_size: 32
batch_size: 32
num_microbatches: 16
lr: 0.0001
momentum: 0.9
decay: 5e-4
S: 5
z: 0.5
dp: False
epochs: 10
save_on_epochs: [5, 10]
optimizer: Adam

mu: 0.9
key_to_drop: 8
number_of_entries: 1000
number_of_entries_test: 1000

save_model: True
dataset: celeba
model: resnet
densenet_depth: 100
scheduler: True

image_dir: data/celeba/img_align_celeba/img_align_celeba
attr_path: data/celeba/list_attr_celeba.csv
selected_attr: [Male]

