name: smiling_celeba_non_dp_18k_female
test_batch_size: 128
batch_size: 256
num_microbatches: 256
lr: 0.00005
momentum: 0.9
decay: 5e-4
S: 5
z: 0.5
mu: 0.9
dp: False
epochs: 60
save_on_epochs: [10, 20, 40, 60]
optimizer: Adam
scheduler: False

save_model: True
dataset: celeba
model: resnet

image_dir: data/celeba/img_align_celeba/img_align_celeba
attr_path: data/celeba/imbalanced_attr/18k_female.csv
selected_attr: Smiling
protected_attr: Male
labels: [0, 1]
multi_gpu: False

