test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.05
momentum: 0.5
decay: 0
S: 1
z: 1.1
dp: False
epochs: 40
save_on_epochs: [10, 50, 100, 200]

mu: 1.0
ds_size: 60000

key_to_drop: 8
number_of_entries: 1000
number_of_entries_test: 1000


save_model: False
dataset: dif
model: resnet
densenet_depth: 100
scheduler: False


class_list: /home/eugene/dpf/data/dif/gender_list.pt
root_dir: /home/eugene/dpf/data/dif/images/
crop_list: /home/eugene/dpf/data/dif/boxes_list.pt

indices_train: /home/eugene/dpf/data/dif/gender_train_list.pt
indices_test: /home/eugene/dpf/data/dif/gender_test_list.pt