test_batch_size: 25
batch_size: 32
num_microbatches: 16
lr: 0.0001
momentum: 0.9
decay: 5e-4
S: 5
z: 0.2
dp: True
epochs: 60
save_on_epochs: [5, 10, 50, 100, 200]
optimizer: Adam

mu: 0.9
ds_size: 60000

key_to_drop: 5
number_of_entries: 500
number_of_entries_test: 1000
inat_drop_proportional: True

save_model: False
dataset: inat
model: inception
densenet_depth: 100
scheduler: True
